services:
  ingestion:
    build: ./ingestion
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=localhost

  rag:
    build: ./rag
    ports:
      - "8001:8001"
    environment:
      - QDRANT_HOST=localhost

  vector-db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: