services:
  ingestion:
    build: ./main/ingestion
    ports:
      - "8000:8000"
    environment:
      - VECTOR_DB_HOST=localhost
      - VECTOR_DB_PORT=6333
    networks:
      - hotmart

  rag:
    build: ./main/rag
    ports:
      - "8001:8001"
    environment:
      - VECTOR_DB_HOST=localhost
      - VECTOR_DB_PORT=6333
    networks:
      - hotmart

  vector-db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - hotmart

volumes:
  qdrant_data:

networks:
  hotmart:
    driver: bridge